name = "ModelConstructors"
uuid = "e47e5152-bd14-11e9-1b46-c951f0a7041d"
authors = ["William Chen <william.chen@ny.frb.org", "Ethan Matlin <ethanmatlin@gmail.com>", "Reca Sarfati <rebecca.sarfati@ny.frb.org"]
version = "0.1.4"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nullables = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "0.7, 1.0, 1.1"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DSGE = "6cf23378-2c47-544c-b0c3-6efefe57ca11"
SMC = "c6043b28-c053-11e9-348c-19d3cb73bbb3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "DSGE", "SMC", "Test"]
